### ISSUE TITLE
XM+ RSSI not working

### ISSUE THREAD

**Issue by 2mod** [RaceFlightOne/RaceFlightOne#203] opened 2017-10-08 15:49 UTC
it would be awesome having rssi working for the xm+
ive tried every little trick on the taranis i could think of, to get some sort of rssi, but it seems like the fc isnt forwarding the rssi signal on one of the channels (usually ch16)

cheers guys!

**Comment by PGIII** [comment] 2017-12-12 18:25
closed since this is a duplicate of another issue

**Closed by PGIII** 2017-12-12 18:25 UTC
