### ISSUE TITLE
GUI 307 or 306.116 FW issue

### ISSUE THREAD

**Issue by chargerdude70** [RaceFlightOne/RaceFlightOne#171] opened 2017-07-24 00:34 UTC
When changing Rates in "Profile 1" to very tame rates, I get a straight line in the graph and 1deg/sec  roll for all axis.

![capture](https://user-images.githubusercontent.com/6600288/28504456-74b39202-6fe5-11e7-843a-c2b64bf817c0.PNG)

**Comment by TomT4S** [comment] 2017-08-01 12:07
I can reproduce this issue - 

It appears when saving different profiles, the rates drop down box reverts to "Rates" which seems to be a null value. When re-choosing an option in the drop down, the rates will work. 

Also noticed smoothing reverts to a "0" value, which could cause full throttle on arm, even though the GUI does not allow the smoothing to be 0, once unplugged and re-plugged in the "0" value is retained. 

I have not tested this real world though.

**Comment by Arti3DPlayer** [comment] 2017-08-01 12:10
@TomT4S +1 seems it is board save issue @rs2k

**Comment by TomT4S** [comment] 2017-08-02 02:12
Fixed in 309.

**Closed** 2017-08-06 19:46 UTC
Labels: GUI
